config/routes.rb
Rails.application.routes.draw do
  
  #Rota crud
  get 'users/crud', to: 'users#crud', as: :crud
  
  #Rotas do scaffold
  
  resources :inscritos
  resources :events
  resources :rooms
  resources :accomms
  resources :rooms
  resources :federations
  resources :ejs
  resources :pasers
  resources :palestras
  resources :password_resets, only: [:new, :create, :edit, :update]

  
  #Rotas para a home page
  
  get 'static_pages/home', as: :home
  root 'static_pages#home'
  
  #Rota das acomodações
  
  get 'accomms/:id/rooms', to: 'accomms#index_rooms', as: :index_rooms
  
  #Rota para busca de quartos com camas especificas
  
  get 'accomms/:id/rooms/:beds', to: 'accomms#especific_rooms', as: :especific_rooms

  #Rotas do user_controller
  
  
  
  #Rota para as transferências
  
  get 'userdbs/transferencia', to: 'userdbs#transfer_type', as: :transfer_type
  post 'userdbs/transferencia', to: 'userdbs#create', as: :transfer_type_post
  
  #Rota de relação palestra-usuario
  
  post 'palestras/:id/entrar', to: 'palestras#paser', as: :pasers_new2
  
  
  # Rota para a inscrição dos usuários nos quartos
  post 'rooms/:id/entrar', to: 'rooms#insc_room', as: :insc_room
 
  # Rota de confirmação
  get 'alteration', to: 'userdbs#alteration', as: :alteration
  
  
  #Rota para download de arquivos da palestra
  
  get '/download_file', to: 'palestras#download_file', as: :download_file
  
  # Rotas do user_session_controller
  
  get '/login', to: 'user_session#new', as: :login
  post '/login', to: 'user_session#create'
  delete '/logout', to: 'user_session#destroy', as: :logout

  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :userdbs
end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :profile_photo, PictureUploader
    
     def self.to_csv
        users = User.all
        attributes = ["user_id" , "Usuario"]
    
        CSV.generate(headers: true) do |csv|
          csv << attributes
    
          all.each do |user|
            csv << [user.id, user.name]
          end
        end
     end
    
    attr_accessor :reset_token
    before_create :confirmation_token
    before_save :downcase_email
    
    has_secure_password
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, length: {in: 10..50}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :cpf, uniqueness: true, presence: true, allow_nil: true
    validates :password, length: {in: 3..50, presence: true, allow_nil: true}
    
    belongs_to :ej
    belongs_to :room
    has_many :userdbs, dependent: :destroy
    has_many :pasers, dependent: :destroy
    has_many :inscritos, dependent: :destroy
     
     # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end

     
     # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
     
    
    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
    # Returns a random token.
    def User.new_token
       SecureRandom.urlsafe_base64
    end
    
    #Downcade every email.
    def downcase_email
       self.email = email.downcase
    end
    
    # Métodos da recuperaçaõ de senha.
    def create_reset_digest
       self.reset_token = User.new_token
       update_attribute(:reset_digest,  User.digest(reset_token))
       update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    def send_password_reset_email
       UserMailer.password_reset(self).deliver_now
    end
        
    private
     def confirmation_token
       if self.confirm_token.blank?
         self.confirm_token = SecureRandom.urlsafe_base64.to_s
       end
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_user, only: [:new, :create]
  before_action :is_admin, except: [:show,:email_activate,:confirm_email]
  before_action :require_user
 
  
  
  
  def crud
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end
  
  def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
  end
  def confirm_email
      user = User.find_by_confirm_token(params[:id])
      if user
        user.email_activate
        flash[:success] = "Bem-vindo, seu e-mail foi ativado com sucesso!"
        redirect_to login_path
      else
        flash[:error] = "Sorry. User does not exist"
        redirect_to root_url
      end
  end
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
        format.html
        format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @ejs = Ej.all
    @friends = User.where(:room_id => current_user.room_id)
    @friends = @friends.where.not(:id => current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
    @ej = Ej.first
  end

  # GET /users/1/edit
  def edit
  end
  

  # POST /users
  # POST /users.json
  def create
     @user = User.new(user_params)
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        flash[:success] = "Please confirm your email address to continue"
        redirect_to root_path
      else
        respond_to do |format|
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if !@user.ej_id.nil?
      ejt = Ej.find(@user.ej_id)
      if !ejt.nil?
        ejt.counter = ejt.users.count
        ejt.save
      end
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to crud_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :cpf, :cep, :tel, :ej_id, :profile_photo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def is_admin
        if !current_user.admin
            redirect_to login_path
        end
    end
    
    def correct_user
        if current_user != @user
            redirect_to login_path
        end
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <% if !current_user %>
    <div class="field">
      <%= f.label :cpf%>
      <%= f.text_field :cpf %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :cep %>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :email %> 
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Foto %> 
    <%= f.file_field :profile_photo %>
  </div>
  <% if !@ej.nil? %>
  <div class="field">
    <%= f.label :ej %> 
    <%= f.collection_select :ej_id, Ej.all, :id, :name %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :password %> 
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation%> 
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions meio">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/crud.html.erb
<% provide(:title, "Usuarios | ")%>
<p id="notice"><%= notice %></p>

<div class="col-3 caixa">
<h1>Users Admin</h1>

<table id = "users_adm" >
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Exibir', user, :class=>"exibir" %></td>
        <td><%= link_to 'Editar', edit_user_path(user), :class=>"editar" %></td>
        <td><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="centro">
<%= will_paginate @users%>
</div>
<p class="meio">
<a href="/user">Baixar CSV dos inscritos</a>
</p>
</div>
<script>
  $('#users_adm').DataTable({});
</script>

app/views/users/edit.html.erb
<div class="col-3 caixa">
    <h2>Editar Usuário</h2>
    
    <%= render 'form' %>
    
    <p class="meio">
        <%= link_to 'Exibir', @user, :class=>"exibir" %>
        <%= link_to 'Voltar', users_path, :class=>"exibir" %>
    </p>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>

<div class="col-3 caixa">
  <h2>Usuários</h2>
  <p class="meio">
    <%= link_to 'Novo Inscrito', new_user_path, :class=>"novo" %>
  </p>
  <ul class="lista">
    
    <% @users.each do |user| %>
    
      <li class="lista-item">
        <ul class="sublista">
          <li>
            <h3 class="meio"><%= user.name %> </h3>
          </li>
          <li>
            <strong>CPF: </strong>
            <%= user.cpf %>
          </li>
          <li>
            <strong>CEP: </strong>
            <%= user.cep %>
          </li>
          <li>
            <strong>TELEFONE: </strong>
            <%= user.tel %>
          </li>
          <li>
            <strong>EMAIL: </strong>
            <%= user.email %>
          </li>
          <% if !user.ej_id.nil? %>
            <li>
              <strong>EJ: </strong>
              <%= user.ej %>
            </li>
          <% end %>
        </ul>
        <p class="meio">
          <%= link_to 'Exibir', user, :class=>"exibir" %>
          <%= link_to 'Editar', edit_user_path(user), :class=>"editar" %>
          <%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
        </p>
      </li>
    <% end %>
  </ul>
  <div class="centering">
    <a class="centering" href="/users.csv" class="novo">Baixar CSV dos inscritos</a>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-3 caixa">
    <h2>Novo Usuário</h2>
    
    <%= render 'form' %>
    
    <p class="meio">
        <%= link_to 'Voltar', users_path, :class=>"exibir" %>
    </p>
</div>

app/views/users/show.html.erb
  <%= notice %>

<div class="col-1 caixa">
  <h2>Perfil</h2>
  <div class="top10"></div>
    <figure>
       <%= image_tag(@user.profile_photo) %>
    </figure>
    <p>
      <strong>Nome:</strong>
      <%= @user.name %>
    </p>
    <p>
      <strong>Email:</strong>
        <%= @user.email %>
    </p>
    <p>
      <strong>CPF:</strong>
        <%= @user.cpf %>
    </p>
    <p>
      <strong>CEP:</strong>
        <%= @user.cep %>
    </p>
    <p>
      <strong>Telefone:</strong>
        <%= @user.tel %>
    </p>
    <% if @user.ej.presence %>
      <p>
        <strong>Ej:</strong>
          <%= @user.ej.name %>
      </p>
    <!--<p>-->
    <!--  <strong>Fereração:</strong>-->
        <%#= @user.ej.federation.name %>
    <!--</p>-->
    <p>
    <% end %>
      <!--EMPRESA JUNIOR - FEDERAÇÃO - FEDERADA (OU NÃO)-->
    </p>
    <p>
      <strong>Companheiros de quarto: </strong>
      <!--ACOMODACAO-->
    </p>
    <div id="companheiros-quarto">
      <% if !@user.room_id.nil? %>
      <% @friends.each do |friend| %>
        <p class="meio">
          <%= friend.name %>
        </p>
        <figure class="companheiro">
          <%= image_tag(friend.profile_photo) %>
        </figure>
      <% end %>
      <% end %>
      
  <div class="top10"></div>
    <p class="meio">
      <% if logged_in? %>
        <%= link_to "Sair", logout_path, method: :delete, :class=>"apagar"  %>
      <% end %>
      <% if !logged_in? %>
        <%= link_to 'Login', login_path, :class=>"exibir" %>
      <% end %>
  
      <%= link_to 'Editar', edit_user_path(@user), :class=>"editar"  %>
    </p>
  </div>
  <div class="top10"></div>  
</div>

<div class="col-2 caixa">
  <h2>Ranking</h2>
  <ul class="lista" id="ranking">
  <% @ejs.order("counter DESC").limit(5).each do |ej| %>
    <li class="lista-item">
      <ul class="sublista">
        <li>
          <h3 class="meio">
            <%= ej.name %>
          </h3>
        </li>
        <% if ej.federation %>
        <li>
          <strong>Federação: </strong>
          <%= ej.federation.name%>
        </li>
        <% end %>
        <li>
          <strong>Cidade: </strong>
          <%= ej.city %>
        </li>
        <li>
          <strong>Contador: </strong>
          <%= ej.counter %>
        </li>
      </ul>
    </li>
    <% end %>
  </ul>
</div>

<div class="col-3 caixa">
  <!--PROGRAMAÇÃO ESCOLHIDA PELO USUÁRIO-->
  <h2>Programação</h2>
  <% current_user.pasers.each do |paser|%>
  <ul class="lista">
    
    <li class="lista-item">
      <ul class="sublista">
        <li>
          <h3 class="meio"><%= paser.palestra.title %> </h3>
          <!--TAG RAILS-->
        </li>
        <li>
          <strong>Orador: </strong>
          <%= paser.palestra.speaker %>
          <!--TAG RAILS-->
        </li>
        <li>
          <strong>Data: </strong>
          <%= paser.palestra.dat %>
          <!--TAG RAILS-->
        </li>
        
        <li>
          <strong>Descrição: </strong>
          <%= paser.palestra.description %>
          <!--TAG RAILS-->
        </li>
        
    
      </ul>
     
    </li>
  </ul>
  <% end %>
</div>