config/routes.rb
Rails.application.routes.draw do
  
  #Rota crud
  get 'users/crud', to: 'users#crud', as: :crud
  
  #Rotas do scaffold
  
  resources :inscritos
  resources :events
  resources :rooms
  resources :accomms
  resources :rooms
  resources :federations
  resources :ejs
  resources :pasers
  resources :palestras
  resources :password_resets, only: [:new, :create, :edit, :update]

  
  #Rotas para a home page
  
  get 'static_pages/home', as: :home
  root 'static_pages#home'
  
  #Rota das acomodações
  
  get 'accomms/:id/rooms', to: 'accomms#index_rooms', as: :index_rooms
  
  #Rota para busca de quartos com camas especificas
  
  get 'accomms/:id/rooms/:beds', to: 'accomms#especific_rooms', as: :especific_rooms

  #Rotas do user_controller
  
  
  
  #Rota para as transferências
  
  get 'userdbs/transferencia', to: 'userdbs#transfer_type', as: :transfer_type
  post 'userdbs/transferencia', to: 'userdbs#create', as: :transfer_type_post
  
  #Rota de relação palestra-usuario
  
  post 'palestras/:id/entrar', to: 'palestras#paser', as: :pasers_new2
  
  
  # Rota para a inscrição dos usuários nos quartos
  post 'rooms/:id/entrar', to: 'rooms#insc_room', as: :insc_room
 
  # Rota de confirmação
  get 'alteration', to: 'userdbs#alteration', as: :alteration
  
  
  #Rota para download de arquivos da palestra
  
  get '/download_file', to: 'palestras#download_file', as: :download_file
  
  # Rotas do user_session_controller
  
  get '/login', to: 'user_session#new', as: :login
  post '/login', to: 'user_session#create'
  delete '/logout', to: 'user_session#destroy', as: :logout

  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :userdbs
end

app/models/accomm.rb
class Accomm < ActiveRecord::Base
    mount_uploader :accomm_photo, PictureUploader
    has_many :rooms, dependent: :destroy
    
    
    validates :accomm_photo, presence: true
    validates :name, presence: true
    validates :tipo, presence: true
    validates :adress, presence: true
end

app/controllers/accomms_controller.rb
class AccommsController < ApplicationController
  before_action :set_accomm, only: [:show, :edit, :update, :destroy, :index_rooms, :especific_rooms]
  before_action :is_admin, except: [:show,:index,:index_rooms,:especific_rooms]

  # GET /accomms
  # GET /accomms.json
  def index
    @accomms = Accomm.all
  end
  
  def index_rooms
    @rooms = @accomm.rooms
  end
  
  def especific_rooms
    @rooms = Room.where(:beds => params[:beds])
  end
  # GET /accomms/1
  # GET /accomms/1.json
  def show
  end

  # GET /accomms/new
  def new
    @accomm = Accomm.new
  end

  # GET /accomms/1/edit
  def edit
  end

  # POST /accomms
  # POST /accomms.json
  def create
    @accomm = Accomm.new(accomm_params)

    respond_to do |format|
      if @accomm.save
        format.html { redirect_to @accomm, notice: 'Accomm was successfully created.' }
        format.json { render :show, status: :created, location: @accomm }
      else
        format.html { render :new }
        format.json { render json: @accomm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accomms/1
  # PATCH/PUT /accomms/1.json
  def update
    respond_to do |format|
      if @accomm.update(accomm_params)
        format.html { redirect_to @accomm, notice: 'Accomm was successfully updated.' }
        format.json { render :show, status: :ok, location: @accomm }
      else
        format.html { render :edit }
        format.json { render json: @accomm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accomms/1
  # DELETE /accomms/1.json
  def destroy
    @accomm.destroy
    respond_to do |format|
      format.html { redirect_to accomms_url, notice: 'Accomm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accomm
      @accomm = Accomm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accomm_params
      params.require(:accomm).permit(:adress, :tipo, :name,:accomm_photo)
    end
end

app/helpers/accomms_helper.rb
module AccommsHelper
end

app/views/accomms/_form.html.erb
<%= form_for(@accomm) do |f| %>
  <% if @accomm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accomm.errors.count, "error") %> prohibited this accomm from being saved:</h2>

      <ul>
      <% @accomm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :nome %> 
    <%= f.text_field :name, class: :input %>
  </div>
  <div class="field">
    <%= f.label :Local %> 
    <%= f.text_field :adress, class: :input %>
  </div>
  <div class="field">
    <%= f.label :tipo %> 
    <%= f.text_field :tipo, class: :input %>
  </div>
  <div class="field">
    <%= f.label :Foto %> 
    <%= f.file_field :accomm_photo %>
  </div>
  <div class="actions meio">
    <%= f.submit :Criar, class: :submit %>
  </div>
<% end %>

app/views/accomms/edit.html.erb
<div class="col-3 caixa">
    <h2>Editar Acomodação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Exibir', @accomm, :class=>"exibir"  %>
        <%= link_to 'Voltar', accomms_path, :class=>"editar"  %>
    </p>
</div>

app/views/accomms/especific_rooms.html.erb
  <% @rooms.each do |room| %>
      <div class="caixa col-1">
        <p class="room-type">
          <%= room.accomm.tipo%> 
          <%= room.accomm.name %>
        </p>
        <figure>
          <%= image_tag(room.accomm.accomm_photo) %>
        </figure>
        
        <div>
        
          
          
          
          
          
          <div class="clear"></div>
          <p class="meio">
            <%= link_to 'Show', room, class: :but, :class=>"exibir" %>
            <% if current_user.admin %>
              <%= link_to 'Edit', edit_room_path(room), :class=>"editar" %>
              <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
            <% end %>
          </p>
        </div>
      </div>
      
    <% end %>

app/views/accomms/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-3 caixa">
  <h2>Acomodações</h2>
  <p class="meio">
    <%= link_to 'Nova Acomodação', new_accomm_path, :class=>"novo" %>
  </p>
  <ul class="lista">
    
    <% @accomms.each do |accomm| %>
    
      <li class="lista-item">
        <ul class="sublista">
          <li>
            <h3 class="meio">
              <%= accomm.name %> 
            </h3>
          </li>
          <li>
            <strong>Tipo: </strong>
            <%= accomm.tipo %>
          </li>
          <li>
            <strong>Local: </strong>
            <%= accomm.adress %>
          </li>
        </ul>
        <p class="meio">
          <a href="accomms/<%= accomm.id %>/rooms" class="exibir">Quartos</a>
          <% if current_user.admin %>
          <%= link_to 'Editar', edit_accomm_path(accomm), :class=>"editar" %>
          <%= link_to 'Apagar', accomm, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
          <% end %>
        </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/accomms/index_rooms.html.erb
<!--<p class="alert alert-success">-->
  <%= notice %>
<!--</p>-->

<div id="titulo">
  <div class="col-1 caixa centro">
    <h1>Quartos</h1>
    <p class="meio">
      <% if current_user.admin %>
        <%= link_to 'New Room', new_room_path, :class=>"novo" %>
      <% end %>
    </p>
  </div>
</div>

  <div class="col-3 caixa">
    <h2>Opções</h2>
    <p class="meio">
      <a href="rooms/2/" class="novo">2 camas</a>
      <a href="rooms/3/" class="novo">3 camas</a>
      <a href="rooms/4/" class="novo">4 camas</a>
    </p>
  </div>

    <% @rooms.each do |room| %>
      <div class="caixa col-1">
        <p class="room-type">
          <%= room.accomm.tipo%> 
          <%= room.accomm.name %>
        </p>
        <figure>
          <%= image_tag(room.accomm.accomm_photo) %>
        </figure>
        
        <div class="quartoInfos">
          <li style="text-align:center;margin-top:20px;">
            <strong>Vagas: </strong>
            <%= User.where(:room_id => room.id).count %>/<%= room.beds %>
          </li>
          <p><strong>Hospedados</strong></p>
          <div class="centro">
          <% room.users.each do |wow| %>
            <figure class="companheiro">
              <%= image_tag(wow.profile_photo) if wow.profile_photo.present? %> 
            </figure>
          <% end %>
          </div>
          <p class="meio">
            <%= link_to 'Exibir', room, class: :but, :class=>"exibir" %>
            <% if current_user.admin %>
              <%= link_to 'Editar', edit_room_path(room), :class=>"editar" %>
              <%= link_to 'Apagar', room, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
            <% end %>
          </p>
        </div>
      </div>
      
    <% end %>
<br>
<div class="limpar"></div>
</body>

app/views/accomms/new.html.erb
<div class="col-3 caixa">
    <h2>Nova Acomodação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Voltar', accomms_path, :class=>"exibir" %>
    </p>
</div>

app/views/accomms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3 caixa">
  <p>
    <strong>Endereço:</strong>
    <%= @accomm.adress %>
  </p>
  
  <p>
    <strong>Tipo:</strong>
    <%= @accomm.tipo %>
  </p>
  <p class="meio">
    <%= link_to 'Edit', edit_accomm_path(@accomm), :class=>"editar" %>
    <%= link_to 'Back', accomms_path, :class=>"exibir" %>
  </p>
</div>