config/routes.rb
Rails.application.routes.draw do
  
  #Rota crud
  get 'users/crud', to: 'users#crud', as: :crud
  
  #Rotas do scaffold
  
  resources :inscritos
  resources :events
  resources :rooms
  resources :accomms
  resources :rooms
  resources :federations
  resources :ejs
  resources :pasers
  resources :palestras
  resources :password_resets, only: [:new, :create, :edit, :update]

  
  #Rotas para a home page
  
  get 'static_pages/home', as: :home
  root 'static_pages#home'
  
  #Rota das acomodações
  
  get 'accomms/:id/rooms', to: 'accomms#index_rooms', as: :index_rooms
  
  #Rota para busca de quartos com camas especificas
  
  get 'accomms/:id/rooms/:beds', to: 'accomms#especific_rooms', as: :especific_rooms

  #Rotas do user_controller
  
  
  
  #Rota para as transferências
  
  get 'userdbs/transferencia', to: 'userdbs#transfer_type', as: :transfer_type
  post 'userdbs/transferencia', to: 'userdbs#create', as: :transfer_type_post
  
  #Rota de relação palestra-usuario
  
  post 'palestras/:id/entrar', to: 'palestras#paser', as: :pasers_new2
  
  
  # Rota para a inscrição dos usuários nos quartos
  post 'rooms/:id/entrar', to: 'rooms#insc_room', as: :insc_room
 
  # Rota de confirmação
  get 'alteration', to: 'userdbs#alteration', as: :alteration
  
  
  #Rota para download de arquivos da palestra
  
  get '/download_file', to: 'palestras#download_file', as: :download_file
  
  # Rotas do user_session_controller
  
  get '/login', to: 'user_session#new', as: :login
  post '/login', to: 'user_session#create'
  delete '/logout', to: 'user_session#destroy', as: :logout

  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :userdbs
end

app/models/federation.rb
class Federation < ActiveRecord::Base
    mount_uploader :palestra_file, FileUploader
    has_many :ejs
    
    validates :name, length: {in: 2..50}
    
end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController
  before_action :set_federation, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  before_action :is_admin

  # GET /federations
  # GET /federations.json
  def index
    @federations = Federation.all
  end

  # GET /federations/1
  # GET /federations/1.json
  def show
  end

  # GET /federations/new
  def new
    @federation = Federation.new
  end

  # GET /federations/1/edit
  def edit
  end

  # POST /federations
  # POST /federations.json
  def create
    @federation = Federation.new(federation_params)

    respond_to do |format|
      if @federation.save
        format.html { redirect_to @federation, notice: 'Federation was successfully created.' }
        format.json { render :show, status: :created, location: @federation }
      else
        format.html { render :new }
        format.json { render json: @federation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /federations/1
  # PATCH/PUT /federations/1.json
  def update
    respond_to do |format|
      if @federation.update(federation_params)
        format.html { redirect_to @federation, notice: 'Federation was successfully updated.' }
        format.json { render :show, status: :ok, location: @federation }
      else
        format.html { render :edit }
        format.json { render json: @federation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /federations/1
  # DELETE /federations/1.json
  def destroy
    @federation.destroy
    respond_to do |format|
      format.html { redirect_to federations_url, notice: 'Federation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_federation
      @federation = Federation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def federation_params
      params.require(:federation).permit(:name)
    end
end

app/helpers/federations_helper.rb
module FederationsHelper
end

app/views/federations/_form.html.erb
<%= form_for(@federation) do |f| %>
  <% if @federation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@federation.errors.count, "error") %> prohibited this federation from being saved:</h2>

      <ul>
      <% @federation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions meio">
    <%= f.submit %>
  </div>
<% end %>

app/views/federations/edit.html.erb
<div class="col-3 caixa">
    <h2>Editar Federação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Exibir', @federation, :class=>"exibir" %>
        <%= link_to 'Voltar', federations_path, :class=>"exibir" %>
    </p>
</div>

app/views/federations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3 caixa">
  <h2>Federações</h2>
  <p class="meio">
    <%= link_to 'Nova Federação', new_federation_path, :class=>"novo" %>
  </p>
  <ul class="lista">
    
    <% @federations.each do |federation| %>
    
      <li class="lista-item">
        <ul class="sublista">
          <li>
            <h3 class="meio">
              <%= federation.name %> 
            </h3>
          </li>
        </ul>
        <p class="meio">
          <%= link_to 'Exibir', federation, :class=>"exibir" %>
          <%= link_to 'Editar', edit_federation_path(federation), :class=>"editar" %>
          <%= link_to 'Apagar', federation, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
        </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/federations/new.html.erb
<div class="col-3 caixa">
    <h2>Nova Federação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Voltar', federations_path, :class=>"exibir" %>
    </p>
</div>

app/views/federations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3 caixa">
  <p>
    <strong>Name:</strong>
    <%= @federation.name %>
  </p>
  <p class="meio">
    <%= link_to 'Edit', edit_federation_path(@federation), :class=>"editar" %> |
    <%= link_to 'Back', federations_path, :class=>"exibir" %>
  </p>
</div>