config/routes.rb
Rails.application.routes.draw do
  
  #Rota crud
  get 'users/crud', to: 'users#crud', as: :crud
  
  #Rotas do scaffold
  
  resources :inscritos
  resources :events
  resources :rooms
  resources :accomms
  resources :rooms
  resources :federations
  resources :ejs
  resources :pasers
  resources :palestras
  resources :password_resets, only: [:new, :create, :edit, :update]

  
  #Rotas para a home page
  
  get 'static_pages/home', as: :home
  root 'static_pages#home'
  
  #Rota das acomodações
  
  get 'accomms/:id/rooms', to: 'accomms#index_rooms', as: :index_rooms
  
  #Rota para busca de quartos com camas especificas
  
  get 'accomms/:id/rooms/:beds', to: 'accomms#especific_rooms', as: :especific_rooms

  #Rotas do user_controller
  
  
  
  #Rota para as transferências
  
  get 'userdbs/transferencia', to: 'userdbs#transfer_type', as: :transfer_type
  post 'userdbs/transferencia', to: 'userdbs#create', as: :transfer_type_post
  
  #Rota de relação palestra-usuario
  
  post 'palestras/:id/entrar', to: 'palestras#paser', as: :pasers_new2
  
  
  # Rota para a inscrição dos usuários nos quartos
  post 'rooms/:id/entrar', to: 'rooms#insc_room', as: :insc_room
 
  # Rota de confirmação
  get 'alteration', to: 'userdbs#alteration', as: :alteration
  
  
  #Rota para download de arquivos da palestra
  
  get '/download_file', to: 'palestras#download_file', as: :download_file
  
  # Rotas do user_session_controller
  
  get '/login', to: 'user_session#new', as: :login
  post '/login', to: 'user_session#create'
  delete '/logout', to: 'user_session#destroy', as: :logout

  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :userdbs
end

app/models/room.rb
class Room < ActiveRecord::Base
  mount_uploader :room_photo, PictureUploader
  
  belongs_to :accomm
  has_many :users, dependent: :nullify
  
  validates :accomm_id, presence: true
  validates :beds, :inclusion => {:in => 1..4}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy, :insc_room]
  before_action :verify_vacancies, only: [:entry_room]
  before_action :require_user
  before_action :is_admin, except: [:index,:show,:insc_room]
  
  def verify_vacancies
    users = @room.users.count
    if users == @room.beds
      redirect_to rooms_path
      flash[:error] = "Limite de vagas atingida.."
    end
  end
  
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
    @users = User.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end
  
  def insc_room
    if current_user.room_id.nil?
      current_user.room_id = @room.id
      current_user.save
    else
      current_user.room_id = nil
      current_user.save
    end
    room = Room.find(params[:id])
    respond_to do |format|
      format.html{redirect_to room}
      format.js {}
    end
      
  end
  


  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:accomm_id, :beds)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :accomm_id %>
    <%= f.collection_select :accomm_id, Accomm.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :beds %>
    <%= f.number_field :beds %>
  </div>
  <div class="field">
    <%= f.label :Foto %> 
    <%= f.file_field :room_photo %>
  </div>
  <div class="actions meio">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_inscricao.html.erb
<% if current_user.room_id == @room.id || !current_user.room_id %>
<% if current_user.room_id.nil? %>
    <p id="entrar" class="meio"><%= link_to "Entrar",  insc_room_path, method: :post, remote: true, authenticity_token: true, :class=>"exibir" %></p>
<% else %>
    <p id="entrar" class="meio"><%= link_to "Sair",  insc_room_path, method: :post, remote: true, authenticity_token: true, :class=>"editar" %></p>
<% end %>
<% end %>

app/views/rooms/edit.html.erb
<div class="col-3 caixa">
    <h2>Editar Acomodação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Exibir', @room, :class=>"exibir" %>
        <%= link_to 'Voltar', rooms_path, :class=>"exibir" %>
    </p>
</div>

app/views/rooms/entry_room.html.erb
<h1>Incrito!</h1>

app/views/rooms/index.html.1.erb
<p id="notice"><%= notice %></p>

<h1>Quartos</h1>


    <% @rooms.each do |room| %>
      <div class="quartoBox">
        <div class="quartoImage"><span><%= room.acomm.tipo</span></div>
        <div class="quartoInfos">
            
        </div>
      </div>
      
    <% end %>
        <%= link_to 'Show', room %>
       <%= link_to 'Edit', edit_room_path(room) %>
        ><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>




<br>

<%= link_to 'New Room', new_room_path %>
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Accomm</th>
      <th>Beds</th>
      <th>Inscritos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.accomm %></td>
        <td><%= room.beds %></td>
        <td><% room.users.each do |wow| %>
            <%= wow.name %>
          <% end %>
          </td>      
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/index.html.erb
<!--<p class="alert alert-success">-->
  <%= notice %>
<!--</p>-->
<div id="titulo">
  <div class="col-1 caixa centro">
    <h1>Quartos</h1>
    <p class="meio">
      <% if current_user.admin %>
        <%= link_to 'New Room', new_room_path, :class=>"novo" %>
      <% end %>
    </p>
  </div>
</div>

    <% @rooms.each do |room| %>
      <div class="caixa col-1">
        <p class="room-type">
          <%= room.accomm.tipo%> 
          <%= room.accomm.name %>
        </p>
        <figure>
          <%= image_tag(room.accomm.accomm_photo) %>
        </figure>
        
        <div class="quartoInfos">
          <% room.users.each do |wow| %>
            <p>
              <%= wow.name %>
            </p>
          <% end %>
          <p class="meio">
          <%= link_to 'Show', room, class: :but, :class=>"exibir" %>
          <% if current_user.admin %>
            <%= link_to 'Edit', edit_room_path(room), :class=>"editar" %>
            <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"apagar" %>
          <% end %>
          </p>
        </div>
      </div>
      
    <% end %>
<div class="limpar"></div>
</body>

app/views/rooms/insc_room.js.erb
$("#entrar").replaceWith("<%= escape_javascript(render('rooms/inscricao')) %>");

app/views/rooms/leave_room.html.erb
<h1>Você saiu do quarto!</h1>

app/views/rooms/new.html.erb
<div class="col-3 caixa">
    <h2>Nova Acomodação</h2>

    <%= render 'form' %>

    <p class="meio">
        <%= link_to 'Voltar', rooms_path, :class=>"exibir" %>
    </p>
</div>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3 caixa">
  <h2>
    <strong>
      <%= @room.accomm.tipo %>
    </strong>
  </h2>
  <p>
    <strong>
      <%= @room.accomm.name %>
      </strong>
  </p>
  
  <p>
    <em>Camas: </em>
    <%= @room.beds %>
  </p>
  <div class="quartoInfos">
    <%= render 'inscricao' %>
    <p class="meio">
      <% if current_user.admin %>
      <%= link_to 'Edit', edit_room_path(@room), :class=>"editar" %>
      <% end %>
      <%= link_to 'Back', rooms_path, :class=>"exibir" %>
      
    </p>
  </div>
</div>